let currentPage='status',showAllExpenses=false;
const main=document.querySelector('main'),summary=document.querySelector('.summary-card'),creditSection=$('creditCardsSection'),budgetSection=document.querySelector('.card.budget-chart:not(#creditCardsSection)'),quickAdd=document.querySelector('.quick-add'),history=document.querySelector('.history-section'),monthRow=document.querySelector('.month-row'),accountTabs=$('accountTabs'),pages={};
function makePage(id,title,subtitle){const page=document.createElement('section');page.className='app-page';page.dataset.page=id;page.innerHTML=`<header class="page-title"><h1>${title}</h1><p>${subtitle}</p></header>`;pages[id]=page;main.appendChild(page);return page}
const statePage=makePage('status','Il tuo mese','Una vista chiara di conti e ultime spese'),budgetPage=makePage('budget','Budget','Controlla disponibilità e plafond'),recurringPage=makePage('recurring','Spese ricorrenti','Pagamenti previsti e prossime scadenze'),categoriesPage=makePage('categories','Categorie','Organizza le spese e assegna i budget');
const stateAccounts=document.createElement('section');stateAccounts.className='state-accounts';stateAccounts.id='stateAccounts';statePage.append(monthRow,accountTabs,summary,stateAccounts,history);budgetPage.append(budgetSection,creditSection);
const recurringCard=document.createElement('section');recurringCard.className='page-card recurring-page-list';recurringCard.innerHTML='<div class="page-title-row"><h2>Le tue ricorrenze</h2><button class="primary-button" id="newRecurringPage">+ Nuova ricorrenza</button></div>';recurringCard.appendChild($('recurringList'));recurringPage.appendChild(recurringCard);
const categoriesCard=document.createElement('section');categoriesCard.className='page-card categories-page-list';categoriesCard.innerHTML='<div class="page-title-row"><h2>Budget mensili</h2><button class="primary-button" id="newCategoryPage">+ Categoria</button></div><p class="privacy-note">Modifica l’importo accanto a ogni categoria: il salvataggio è automatico.</p>';categoriesCard.appendChild($('categoriesList'));categoriesCard.appendChild(document.querySelector('#categoriesDialog .add-row'));categoriesPage.appendChild(categoriesCard);
const expenseDialog=document.createElement('dialog');expenseDialog.id='expenseDialog';expenseDialog.innerHTML='<div class="dialog-close-row"><button type="button" aria-label="Chiudi">×</button></div>';expenseDialog.appendChild(quickAdd);document.body.appendChild(expenseDialog);expenseDialog.querySelector('button').onclick=()=>{expenseDialog.close();resetForm()};
const nav=document.createElement('nav');nav.className='bottom-nav';nav.innerHTML='<button data-page-button="status"><span>⌂</span>Stato</button><button data-page-button="budget"><span>◔</span>Budget</button><button data-page-button="recurring"><span>↻</span>Ricorrenti</button><button data-page-button="categories"><span>▦</span>Categorie</button>';document.body.appendChild(nav);const addButton=document.createElement('button');addButton.className='floating-add';addButton.textContent='+';addButton.setAttribute('aria-label','Aggiungi spesa');document.body.appendChild(addButton);
function openExpense(recurring=false){resetForm();if(recurring){$('isRecurring').checked=true;$('frequencyField').classList.remove('hidden')}expenseDialog.showModal();setTimeout(()=>$('amount').focus(),100)}addButton.onclick=()=>openExpense();$('newRecurringPage').onclick=()=>openExpense(true);$('newCategoryPage').onclick=()=>{$('newCategoryName').focus();categoriesCard.scrollIntoView({behavior:'smooth',block:'end'})};
function setPage(id){currentPage=id;Object.entries(pages).forEach(([key,page])=>page.classList.toggle('active',key===id));document.querySelectorAll('[data-page-button]').forEach(b=>b.classList.toggle('active',b.dataset.pageButton===id));addButton.classList.toggle('hidden',id==='categories');if(id==='recurring')renderRecurring();if(id==='categories')renderSettings();scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('[data-page-button]').forEach(b=>b.onclick=()=>setPage(b.dataset.pageButton));
const originalEdit=editExpense;editExpense=function(id){originalEdit(id);expenseDialog.showModal()};const originalSubmit=$('expenseForm').onsubmit;$('expenseForm').onsubmit=function(event){const valid=parseAmount($('amount').value)>0;originalSubmit(event);if(valid){expenseDialog.close();setPage('status')}};
$('openCategories').onclick=()=>{$('settingsDialog').close();setPage('categories')};$('editBudgets').onclick=()=>setPage('categories');$('openRecurring').onclick=()=>{$('settingsDialog').close();setPage('recurring')};
const showAll=document.createElement('button');showAll.className='show-all';showAll.textContent='Vedi tutte le spese';history.appendChild(showAll);showAll.onclick=()=>{showAllExpenses=!showAllExpenses;enhanceAfterRender()};
function accountOverview(){const items=state.expenses.filter(x=>inView(x.date));$('stateAccounts').innerHTML=state.accounts.map(a=>{if(a.type==='credit'){const used=items.filter(x=>x.accountId===a.id&&x.kind!=='credit_statement').reduce((s,x)=>s+x.amount,0),limit=Number(a.limit)||0,p=limit?Math.round(used/limit*100):0;return`<article class="state-account-card"><span>💳 ${esc(a.name)} · plafond</span><strong>${eur.format(used)}</strong><div class="mini-progress"><i style="width:${Math.min(p,100)}%;background:${p>100?'#d95b4f':p>=80?'#e9a13b':''}"></i></div></article>`}const used=items.filter(x=>x.accountId===a.id&&(x.kind==='credit_statement'||!isCredit(x.accountId))).reduce((s,x)=>s+x.amount,0);return`<article class="state-account-card"><span>● ${esc(a.name)} · uscite mese</span><strong>${eur.format(used)}</strong><div class="mini-progress"><i style="width:${Math.min(used/Math.max(state.budget||used,1)*100,100)}%"></i></div></article>`}).join('')}
function enhanceAfterRender(){accountOverview();const rows=[...$('expenseList').children];rows.forEach((row,i)=>row.classList.toggle('home-hidden',!showAllExpenses&&i>=5));showAll.classList.toggle('hidden',rows.length<=5);showAll.textContent=showAllExpenses?'Mostra solo le ultime':'Vedi tutte le spese'}const coreRender=render;render=function(){coreRender();enhanceAfterRender()};render();setPage('status');
