const endField=document.createElement('label');endField.className='text-field recurring-end-field hidden';endField.id='recurringEndField';endField.innerHTML='<span>Termina il (facoltativo)</span><input id="recurringEndDate" type="date"><small class="future-note">Lascia vuoto per continuare senza scadenza.</small>';$('frequencyField').after(endField);
function recurrenceOccurrences(r,start,end){if(!r.active)return[];const dates=[];let d=r.nextDate,guard=0;while(d<start&&guard++<600)d=advance(d,r.frequency);while(d<=end&&(!r.endDate||d<=r.endDate)&&guard++<700){dates.push(d);d=advance(d,r.frequency)}return dates}
function viewBounds(){const start=`${viewMonth.getFullYear()}-${String(viewMonth.getMonth()+1).padStart(2,'0')}-01`,last=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,0,12);return[start,iso(last)]}
function projectedForView(){const[start,end]=viewBounds(),out=[];for(const r of state.recurring){for(const date of recurrenceOccurrences(r,start,end)){if(state.expenses.some(x=>x.recurringId===r.id&&x.date===date))continue;out.push({id:`forecast-${r.id}-${date}`,amount:r.amount,category:r.category,accountId:r.accountId,note:r.note,date,createdAt:0,kind:'expense',recurringId:r.id,forecast:true})}}return out}
function cleanAfterEnd(){const byId=new Map(state.recurring.map(r=>[r.id,r]));state.expenses=state.expenses.filter(x=>{const r=x.recurringId&&byId.get(x.recurringId);return!r?.endDate||x.date<=r.endDate})}
processRecurring=function(){let changed=false;for(const r of state.recurring.filter(x=>x.active)){let guard=0;while(r.nextDate<=today()&&(!r.endDate||r.nextDate<=r.endDate)&&guard++<240){if(!state.expenses.some(x=>x.recurringId===r.id&&x.date===r.nextDate))state.expenses.push({id:uid(),amount:r.amount,category:r.category,accountId:r.accountId,note:r.note,date:r.nextDate,createdAt:Date.now(),recurringId:r.id,kind:'expense'});r.nextDate=advance(r.nextDate,r.frequency);changed=true}}cleanAfterEnd();if(changed)persistOnly()};
const v5Render=render;render=function(){v5Render();enhanceForecast()};
function enhanceForecast(){const forecasts=projectedForView().filter(x=>(accountFilter==='all'||x.accountId===accountFilter)&&(categoryFilter==='all'||x.category===categoryFilter));if(forecasts.length){const markup=forecasts.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>{const c=cat(x.category),a=account(x.accountId);return`<article class="expense-item forecast-item"><div class="expense-icon">${c.icon}</div><div class="expense-copy"><strong>${esc(x.note||c.label)}<span class="forecast-badge">prevista</span></strong><span>${esc(c.label)} · ${esc(a?.name||'Conto')} · ${dateFmt.format(new Date(x.date+'T12:00:00'))}</span></div><div class="expense-amount">− ${eur.format(x.amount)}</div></article>`}).join('');$('expenseList').insertAdjacentHTML('afterbegin',markup)}
const allForecasts=projectedForView(),selected=account(accountFilter),relevant=accountFilter==='all'?allForecasts:allForecasts.filter(x=>x.accountId===accountFilter),addition=selected?.type==='credit'?relevant.reduce((s,x)=>s+x.amount,0):relevant.filter(x=>!isCredit(x.accountId)).reduce((s,x)=>s+x.amount,0);if(addition>0){const current=state.expenses.filter(x=>inView(x.date)),actual=selected?.type==='credit'?spending(current.filter(x=>x.accountId===selected.id)):cashflow(accountFilter==='all'?current:current.filter(x=>x.accountId===accountFilter));$('monthlyTotal').textContent=eur.format(actual+addition);$('cashflowNote').textContent=`Include ${eur.format(addition)} di spese ricorrenti previste nel mese.`}
enhanceAfterRender()}
renderRecurring=function(){const labels={weekly:'Ogni settimana',monthly:'Ogni mese',yearly:'Ogni anno'};$('recurringList').innerHTML=state.recurring.length?state.recurring.map(r=>`<div class="setting-row"><div class="setting-row-copy"><strong>${cat(r.category).icon} ${esc(r.note||cat(r.category).label)} · ${eur.format(r.amount)}</strong><span>${labels[r.frequency]} · ${esc(account(r.accountId)?.name)} · prossima ${dateFmt.format(new Date(r.nextDate+'T12:00:00'))}</span><span class="end-date">${r.endDate?`Termina ${dateFmt.format(new Date(r.endDate+'T12:00:00'))}`:'Senza scadenza'}</span></div><div class="setting-row-actions"><button data-end-r="${r.id}">Scadenza</button><button data-toggle-r="${r.id}">${r.active?'Pausa':'Riprendi'}</button><button data-delete-r="${r.id}">Elimina</button></div></div>`).join(''):'<p class="empty-compact">Non hai ancora spese ricorrenti.</p>';document.querySelectorAll('[data-end-r]').forEach(b=>b.onclick=()=>{const r=state.recurring.find(x=>x.id===b.dataset.endR),value=prompt('Data finale in formato AAAA-MM-GG. Lascia vuoto per nessuna scadenza:',r.endDate||'');if(value!==null){if(value&&!/^\d{4}-\d{2}-\d{2}$/.test(value))return alert('Usa il formato AAAA-MM-GG.');r.endDate=value||null;cleanAfterEnd();save()}});document.querySelectorAll('[data-toggle-r]').forEach(b=>b.onclick=()=>{const r=state.recurring.find(x=>x.id===b.dataset.toggleR);r.active=!r.active;save()});document.querySelectorAll('[data-delete-r]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare la ricorrenza? Le spese già registrate resteranno.')){state.recurring=state.recurring.filter(x=>x.id!==b.dataset.deleteR);save()}})};
const priorReset=resetForm;resetForm=function(){priorReset();$('recurringEndDate').value='';endField.classList.add('hidden')};$('isRecurring').onchange=()=>{$('frequencyField').classList.toggle('hidden',!$('isRecurring').checked);endField.classList.toggle('hidden',!$('isRecurring').checked)};
$('newRecurringPage').onclick=()=>{resetForm();$('isRecurring').checked=true;$('frequencyField').classList.remove('hidden');endField.classList.remove('hidden');expenseDialog.showModal();setTimeout(()=>$('amount').focus(),100)};
const v5Submit=$('expenseForm').onsubmit;$('expenseForm').onsubmit=function(event){const recurring=$('isRecurring').checked,end=$('recurringEndDate').value,start=$('date').value,before=new Set(state.recurring.map(r=>r.id));if(recurring&&end&&end<start){event.preventDefault();return alert('La data finale non può precedere la prima spesa.')}v5Submit(event);if(recurring){const created=state.recurring.find(r=>!before.has(r.id));if(created){created.endDate=end||null;persistOnly();render()}}};
cleanAfterEnd();syncStatements();persistOnly();render();
