let transactionType='expense';
for(const c of[{id:'stipendio',label:'Stipendio',icon:'💼',incomeOnly:true},{id:'rimborso',label:'Rimborso',icon:'↩️',incomeOnly:true},{id:'regalo',label:'Regalo',icon:'🎁',incomeOnly:true},{id:'altre-entrate',label:'Altre entrate',icon:'＋',incomeOnly:true}])if(!state.categories.some(x=>x.id===c.id))state.categories.push(c);
state.expenses.forEach(x=>{if(x.kind==='credit_statement')x.transactionType='expense';else if(!x.transactionType){const r=x.recurringId&&state.recurring.find(y=>y.id===x.recurringId);x.transactionType=r?.transactionType||'expense'}});state.recurring.forEach(r=>r.transactionType=r.transactionType||'expense');persistOnly();
const typeSwitch=document.createElement('div');typeSwitch.className='transaction-type';typeSwitch.innerHTML='<button type="button" class="active" data-transaction-type="expense">Uscita</button><button type="button" data-transaction-type="income">Entrata</button>';$('expenseId').after(typeSwitch);
function setTransactionType(type){transactionType=type;document.querySelectorAll('[data-transaction-type]').forEach(b=>b.classList.toggle('active',b.dataset.transactionType===type));renderCategories();renderAccountsForType()}
document.querySelectorAll('[data-transaction-type]').forEach(b=>b.onclick=()=>setTransactionType(b.dataset.transactionType));
function renderAccountsForType(){const old=$('account').value,available=transactionType==='income'?state.accounts.filter(a=>a.type!=='credit'):state.accounts;$('account').innerHTML=available.map(a=>`<option value="${a.id}">${a.type==='credit'?'💳':'●'} ${esc(a.name)}</option>`).join('');$('account').value=available.some(a=>a.id===old)?old:available[0]?.id||''}
renderCategories=function(){const available=state.categories.filter(c=>transactionType==='income'?c.incomeOnly:!c.incomeOnly);if(!available.some(c=>c.id===selectedCategory))selectedCategory=available[0]?.id;$('categoryGrid').innerHTML=available.map(c=>`<button type="button" class="category-button ${c.incomeOnly?'income-category':''} ${selectedCategory===c.id?'selected':''}" data-cat="${c.id}"><span>${c.icon}</span>${esc(c.label)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.cat;renderCategories()})};
const baseRenderAccounts=renderAccounts;renderAccounts=function(){baseRenderAccounts();renderAccountsForType()};
spending=function(items){return items.filter(x=>x.kind!=='credit_statement'&&x.transactionType!=='income').reduce((s,x)=>s+x.amount,0)};cashflow=function(items){return items.filter(x=>x.transactionType!=='income'&&(x.kind==='credit_statement'||!isCredit(x.accountId))).reduce((s,x)=>s+x.amount,0)};
projectedForView=function(){const[start,end]=viewBounds(),out=[];for(const r of state.recurring){for(const date of recurrenceOccurrences(r,start,end)){if(state.expenses.some(x=>x.recurringId===r.id&&x.date===date))continue;out.push({id:`forecast-${r.id}-${date}`,amount:r.amount,category:r.category,accountId:r.accountId,note:r.note,date,createdAt:0,kind:'expense',transactionType:r.transactionType||'expense',recurringId:r.id,forecast:true})}}return out};
processRecurring=function(){let changed=false;for(const r of state.recurring.filter(x=>x.active)){let guard=0;while(r.nextDate<=today()&&(!r.endDate||r.nextDate<=r.endDate)&&guard++<240){if(!state.expenses.some(x=>x.recurringId===r.id&&x.date===r.nextDate))state.expenses.push({id:uid(),amount:r.amount,category:r.category,accountId:r.accountId,note:r.note,date:r.nextDate,createdAt:Date.now(),recurringId:r.id,kind:'expense',transactionType:r.transactionType||'expense'});r.nextDate=advance(r.nextDate,r.frequency);changed=true}}cleanAfterEnd();if(changed)persistOnly()};
renderBudgets=function(items){const rows=state.categories.filter(c=>!c.incomeOnly&&Number(state.categoryBudgets[c.id])>0);$('budgetChart').innerHTML=rows.length?rows.map(c=>{const budget=Number(state.categoryBudgets[c.id]),used=items.filter(x=>x.kind!=='credit_statement'&&x.transactionType!=='income'&&x.category===c.id).reduce((s,x)=>s+x.amount,0),p=Math.round(used/budget*100),status=p>100?'over':p>=80?'warning':'';return`<div class="budget-item"><div class="budget-label"><strong>${c.icon} ${esc(c.label)}</strong><span>${eur.format(used)} di ${eur.format(budget)} · ${p>100?eur.format(used-budget)+' oltre':eur.format(budget-used)+' rimasti'}</span></div><div class="budget-track"><div class="budget-fill ${status}" style="width:${Math.min(p,100)}%"></div></div></div>`}).join(''):'<p class="no-budget">Aggiungi un budget per vedere qui il suo andamento.</p>'};
enhanceForecast=function(){const forecasts=projectedForView().filter(x=>(accountFilter==='all'||x.accountId===accountFilter)&&(categoryFilter==='all'||x.category===categoryFilter));if(forecasts.length){$('expenseList').insertAdjacentHTML('afterbegin',forecasts.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>{const c=cat(x.category),a=account(x.accountId),income=x.transactionType==='income';return`<article class="expense-item forecast-item ${income?'income-item':''}"><div class="expense-icon">${c.icon}</div><div class="expense-copy"><strong>${esc(x.note||c.label)}<span class="forecast-badge">prevista</span>${income?'<span class="income-badge">entrata</span>':''}</strong><span>${esc(c.label)} · ${esc(a?.name||'Conto')} · ${dateFmt.format(new Date(x.date+'T12:00:00'))}</span></div><div class="expense-amount ${income?'income-amount':''}">${income?'+':'−'} ${eur.format(x.amount)}</div></article>`}).join(''))}enhanceAfterRender()};
const flowSummary=document.createElement('section');flowSummary.className='flow-summary';flowSummary.innerHTML='<article class="flow-card income"><span>Entrate del mese</span><strong id="incomeTotal">€ 0,00</strong></article><article class="flow-card"><span>Uscite effettive</span><strong id="expenseTotal">€ 0,00</strong></article>';summary.after(flowSummary);
function enhanceIncome(){const actual=state.expenses.filter(x=>inView(x.date)),forecast=projectedForView(),scope=accountFilter==='all'?actual:actual.filter(x=>x.accountId===accountFilter),forecastScope=accountFilter==='all'?forecast:forecast.filter(x=>x.accountId===accountFilter),income=scope.filter(x=>x.transactionType==='income').reduce((s,x)=>s+x.amount,0)+forecastScope.filter(x=>x.transactionType==='income').reduce((s,x)=>s+x.amount,0),out=cashflow(scope)+forecastScope.filter(x=>x.transactionType!=='income'&&!isCredit(x.accountId)).reduce((s,x)=>s+x.amount,0),selected=account(accountFilter);if(selected?.type!=='credit'){$('totalLabel').textContent='Saldo del mese';$('monthlyTotal').textContent=eur.format(income-out);$('cashflowNote').textContent=`Entrate ${eur.format(income)} · Uscite effettive ${eur.format(out)}`;summary.classList.toggle('positive',income-out>=0);summary.classList.toggle('negative',income-out<0)}$('incomeTotal').textContent=eur.format(income);$('expenseTotal').textContent=eur.format(out);flowSummary.classList.toggle('hidden',selected?.type==='credit');document.querySelectorAll('[data-edit]').forEach(b=>{const x=state.expenses.find(e=>e.id===b.dataset.edit);if(x?.transactionType==='income'){const row=b.closest('.expense-item');row.classList.add('income-item');row.querySelector('.expense-amount').textContent=`+ ${eur.format(x.amount)}`;row.querySelector('.expense-copy strong').insertAdjacentHTML('beforeend','<span class="income-badge">entrata</span>')}})}
const v6RenderIncome=render;render=function(){v6RenderIncome();enhanceIncome()};
const v6Reset=resetForm;resetForm=function(){v6Reset();setTransactionType('expense')};const v6Edit=editExpense;editExpense=function(id){const x=state.expenses.find(e=>e.id===id);setTransactionType(x?.transactionType||'expense');v6Edit(id);setTransactionType(x?.transactionType||'expense');$('account').value=x.accountId};
const v6SubmitIncome=$('expenseForm').onsubmit;$('expenseForm').onsubmit=function(event){const type=transactionType,beforeExpenses=new Set(state.expenses.map(x=>x.id)),beforeRecurring=new Set(state.recurring.map(x=>x.id)),editingId=$('expenseId').value;v6SubmitIncome(event);const tx=editingId?state.expenses.find(x=>x.id===editingId):state.expenses.find(x=>!beforeExpenses.has(x.id)&&x.kind!=='credit_statement');if(tx)tx.transactionType=type;const rule=state.recurring.find(x=>!beforeRecurring.has(x.id));if(rule)rule.transactionType=type;persistOnly();render()};
const v6RecurringRender=renderRecurring;renderRecurring=function(){v6RecurringRender();for(const r of state.recurring.filter(x=>x.transactionType==='income')){const button=document.querySelector(`[data-end-r="${r.id}"]`),row=button?.closest('.setting-row');row?.classList.add('income-item');row?.querySelector('.setting-row-copy strong')?.insertAdjacentHTML('beforeend',' <span class="income-badge">entrata</span>')}};
render();
